//
// Created by olcay on 2019-05-08.
//

#ifndef ANNOTATEDTREE_SEARCHTYPE_H
#define ANNOTATEDTREE_SEARCHTYPE_H

enum class SearchType{
    EQUALS, EQUALS_IGNORE_CASE, CONTAINS, MATCHES, STARTS, ENDS, IS_NULL
};
#endif //ANNOTATEDTREE_SEARCHTYPE_H
