//
// Created by Olcay Taner YILDIZ on 31.10.2020.
//

#ifndef DEPENDENCYPARSER_UNIVERSALDEPENDENCYPOSTYPE_H
#define DEPENDENCYPARSER_UNIVERSALDEPENDENCYPOSTYPE_H

/**
 * Enumerator class for Universal Dependency Pos tags
 */
enum class UniversalDependencyPosType {
    ADJ, ADV, INTJ, NOUN, PROPN, VERB, ADP, AUX, CCONJ, DET, NUM, PART, PRON, SCONJ, PUNCT, SYM, X
};

#endif //DEPENDENCYPARSER_UNIVERSALDEPENDENCYPOSTYPE_H
