//
// Created by olcay on 14.03.2019.
//

#ifndef DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H
#define DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H

/**
 * Enumerator class for Universal Dependency tags
 */
enum class UniversalDependencyType{
    ACL, ADVCL, ADVMOD, AMOD, APPOS, AUX, CASE, CC, CCOMP, CLF, COMPOUND, CONJ, COP, CSUBJ, DEP, DET, DISCOURSE,
    DISLOCATED, EXPL, FIXED, FLAT, GOESWITH, IOBJ, LIST, MARK, NMOD, NSUBJ, NUMMOD, OBJ, OBL, ORPHAN, PARATAXIS,
    PUNCT, REPARANDUM, ROOT, VOCATIVE, XCOMP
};
#endif //DEPENDENCYPARSER_UNIVERSALDEPENDENCYTYPE_H
