//
// Created by Olcay Taner Yıldız on 2019-04-24.
//

#ifndef ANNOTATEDSENTENCE_VIEWLAYERTYPE_H
#define ANNOTATEDSENTENCE_VIEWLAYERTYPE_H

/**
 * Enumerated class for annotation layer types
 */
enum class ViewLayerType{
    PART_OF_SPEECH, INFLECTIONAL_GROUP, META_MORPHEME, META_MORPHEME_MOVED, TURKISH_WORD, PERSIAN_WORD, ENGLISH_WORD, WORD, SEMANTICS, NER, DEPENDENCY, PROPBANK, SHALLOW_PARSE, ENGLISH_PROPBANK, ENGLISH_SEMANTICS, FRAMENET
};
#endif //ANNOTATEDSENTENCE_VIEWLAYERTYPE_H
